language: android

addons:
  apt:
    packages:
      - oracle-java8-installer
      - lynx

android:
  components:
    - tools
    - platform-tools
    - tools # appears twice as per Travis docs
    - build-tools-23.0.1
    - build-tools-27.0.2
    - android-4
    - android-10
    - android-19
    - android-23
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-25

  licenses:
    - 'android-sdk-license-.+'

env:
  matrix:
    - ANDROID_TARGET=android-4 ANDROID_ABI=armeabi
    - ANDROID_TARGET=android-10 ANDROID_ABI=armeabi
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a

before_install:
  - yes | sdkmanager "platforms;android-27" # https://github.com/travis-ci/travis-ci/issues/8874
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache/

before_script:
  # Create and start emulator
  - android list targets
  - jdk_switcher use oraclejdk8
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - while [[ `adb shell pm path android` == 'Error'* ]]; do sleep 2; done
  - adb shell input keyevent 82 &

script:
    - cd TextStyling-Java;   ./gradlew -Pci --console=plain :app:testDebug
    - ./gradlew build connectedCheck
    - cd ../TextStyling-Kotlin; ./gradlew -Pci --console=plain :app:testDebug
    - ./gradlew build connectedCheck

after_failure:
  - if [ -f /home/travis/build/jimandreas/android-text/TextStyling-Kotlin/app/build/reports/tests/testDebugUnitTest/index.html ]; then lynx -dump /home/travis/build/jimandreas/android-text/TextStyling-Kotlin/app/build/reports/tests/testDebugUnitTest/index.html; fi
  - if [ -f /home/travis/build/jimandreas/android-text/TextStyling-Java/app/build/reports/androidTests/connected/index.html ];    then lynx -dump /home/travis/build/jimandreas/android-text/TextStyling-Java/app/build/reports/androidTests/connected/index.html; fi
  - if [ -f /home/travis/build/jimandreas/android-text/TextStyling-Kotlin/app/build/reports/androidTests/connected/index.html ]; then lynx -dump  /home/travis/build/jimandreas/android-text/TextStyling-Kotlin/app/build/reports/androidTests/connected/index.html; fi
